### ISSUE TITLE
项目使用 1690774 字节（128%）

### ISSUE THREAD

**Issue by uptell8** [Kerrbty/ESP32C3Clock#1]
项目使用 1690774 字节（128%）的程序存储空间。最大值为 1310720 字节。
 个全局变量使用 40576 个字节（12%）的动态内存，剩下 287104 个字节用于局部变量。最大值为 327680 字节。
项目太大；请参阅 https://support.arduino.cc/hc/en-us/articles/360013825179，以获取减少项目大小的提示。
文本部分超出开发板的可用空间

Compilation error: 文本部分超出开发板的可用空间

**Comment by Kerrbty** [comment]
在 "工具" --> "Partition Scheme"  -->  选一个APP大一点重新编译就可以了 （注意有Flash大小标记不能超）
